import type {
  School,
  Student,
  Teacher,
  FeePayment,
  AttendanceRecord,
  Communication,
  Admission,
  DashboardStats,
  SuperAdminStats,
  TimetableEntry,
  Exam,
} from "./types";

export const dashboardStats: DashboardStats = {
  totalStudents: 2847,
  totalTeachers: 142,
  totalRevenue: 4856000,
  pendingFees: 1234000,
  todayAttendance: 94.2,
  newAdmissions: 156,
  activeClasses: 68,
  upcomingExams: 12,
};

export const superAdminStats: SuperAdminStats = {
  totalSchools: 1247,
  activeSchools: 1089,
  totalStudents: 485600,
  totalRevenue: 28400000,
  monthlyRevenue: 3200000,
  trialSchools: 98,
  expiredSchools: 60,
  supportTickets: 23,
};

export const schools: School[] = [
  {
    id: "1",
    name: "Delhi Public School, Jaipur",
    slug: "dps-jaipur",
    email: "admin@dpsjaipur.edu.in",
    phone: "+91 9876543210",
    address: "Sector 10, Vidyadhar Nagar",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302039",
    board: "CBSE",
    subdomain: "dpsjaipur",
    subscription: "enterprise",
    subscriptionStatus: "active",
    studentCount: 3200,
    teacherCount: 180,
    createdAt: "2024-01-15",
    isActive: true,
  },
  {
    id: "2",
    name: "St. Xavier's High School",
    slug: "st-xaviers",
    email: "info@stxaviers.org",
    phone: "+91 9876543211",
    address: "MG Road, Civil Lines",
    city: "Udaipur",
    state: "Rajasthan",
    pincode: "313001",
    board: "ICSE",
    subdomain: "stxaviers",
    subscription: "professional",
    subscriptionStatus: "active",
    studentCount: 1800,
    teacherCount: 95,
    createdAt: "2024-03-20",
    isActive: true,
  },
  {
    id: "3",
    name: "Modern Academy",
    slug: "modern-academy",
    email: "admin@modernacademy.in",
    phone: "+91 9876543212",
    address: "Vaishali Nagar",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302021",
    board: "RBSE",
    subdomain: "modernacademy",
    subscription: "starter",
    subscriptionStatus: "trial",
    studentCount: 650,
    teacherCount: 35,
    createdAt: "2025-06-01",
    isActive: true,
  },
  {
    id: "4",
    name: "Sunrise International School",
    slug: "sunrise-intl",
    email: "contact@sunriseintl.edu",
    phone: "+91 9876543213",
    address: "Tonk Road",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302015",
    board: "IB",
    subdomain: "sunriseintl",
    subscription: "enterprise",
    subscriptionStatus: "active",
    studentCount: 1200,
    teacherCount: 78,
    createdAt: "2024-06-10",
    isActive: true,
  },
  {
    id: "5",
    name: "Greenfield Public School",
    slug: "greenfield",
    email: "admin@greenfield.edu.in",
    phone: "+91 9876543214",
    address: "Malviya Nagar",
    city: "Delhi",
    state: "Delhi",
    pincode: "110017",
    board: "CBSE",
    subdomain: "greenfield",
    subscription: "professional",
    subscriptionStatus: "expired",
    studentCount: 2100,
    teacherCount: 110,
    createdAt: "2024-02-28",
    isActive: false,
  },
];

export const students: Student[] = [
  {
    id: "1",
    admissionNo: "2024001",
    name: "Aarav Sharma",
    fatherName: "Rajesh Sharma",
    motherName: "Priya Sharma",
    email: "aarav@email.com",
    phone: "+91 9988776601",
    dateOfBirth: "2012-03-15",
    gender: "male",
    bloodGroup: "B+",
    class: "8",
    section: "A",
    rollNo: 1,
    address: "123, Model Town",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302001",
    status: "active",
    admissionDate: "2024-04-01",
    feeStatus: "paid",
    attendancePercent: 96.5,
  },
  {
    id: "2",
    admissionNo: "2024002",
    name: "Ananya Gupta",
    fatherName: "Vikram Gupta",
    motherName: "Neha Gupta",
    phone: "+91 9988776602",
    dateOfBirth: "2011-08-22",
    gender: "female",
    bloodGroup: "A+",
    class: "9",
    section: "B",
    rollNo: 2,
    address: "45, Shanti Nagar",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302004",
    status: "active",
    admissionDate: "2023-04-01",
    feeStatus: "pending",
    attendancePercent: 89.3,
  },
  {
    id: "3",
    admissionNo: "2024003",
    name: "Rohan Patel",
    fatherName: "Amit Patel",
    motherName: "Sunita Patel",
    phone: "+91 9988776603",
    dateOfBirth: "2012-11-05",
    gender: "male",
    bloodGroup: "O+",
    class: "8",
    section: "A",
    rollNo: 3,
    address: "78, Lal Kothi",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302015",
    status: "active",
    admissionDate: "2024-04-01",
    feeStatus: "paid",
    attendancePercent: 92.1,
  },
  {
    id: "4",
    admissionNo: "2024004",
    name: "Ishita Verma",
    fatherName: "Suresh Verma",
    motherName: "Kavita Verma",
    phone: "+91 9988776604",
    dateOfBirth: "2013-01-18",
    gender: "female",
    class: "7",
    section: "C",
    rollNo: 4,
    address: "12, Mansarovar",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302020",
    status: "active",
    admissionDate: "2024-04-01",
    feeStatus: "overdue",
    attendancePercent: 78.4,
  },
  {
    id: "5",
    admissionNo: "2024005",
    name: "Kabir Singh",
    fatherName: "Devendra Singh",
    motherName: "Meera Singh",
    phone: "+91 9988776605",
    dateOfBirth: "2011-05-30",
    gender: "male",
    bloodGroup: "AB+",
    class: "10",
    section: "A",
    rollNo: 5,
    address: "90, Vaishali Nagar",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302021",
    status: "active",
    admissionDate: "2022-04-01",
    feeStatus: "paid",
    attendancePercent: 97.8,
  },
];

export const teachers: Teacher[] = [
  {
    id: "1",
    employeeId: "EMP001",
    name: "Dr. Meena Agarwal",
    email: "meena@school.edu",
    phone: "+91 9876000001",
    subject: "Mathematics",
    qualification: "Ph.D Mathematics",
    experience: 15,
    department: "Science",
    designation: "HOD",
    salary: 85000,
    joiningDate: "2015-07-01",
    status: "active",
  },
  {
    id: "2",
    employeeId: "EMP002",
    name: "Rajendra Kumar",
    email: "rajendra@school.edu",
    phone: "+91 9876000002",
    subject: "Physics",
    qualification: "M.Sc Physics",
    experience: 10,
    department: "Science",
    designation: "Senior Teacher",
    salary: 65000,
    joiningDate: "2018-04-15",
    status: "active",
  },
  {
    id: "3",
    employeeId: "EMP003",
    name: "Sunita Joshi",
    email: "sunita@school.edu",
    phone: "+91 9876000003",
    subject: "English",
    qualification: "M.A English",
    experience: 8,
    department: "Languages",
    designation: "Teacher",
    salary: 55000,
    joiningDate: "2020-01-10",
    status: "active",
  },
  {
    id: "4",
    employeeId: "EMP004",
    name: "Amit Rathore",
    email: "amit@school.edu",
    phone: "+91 9876000004",
    subject: "Computer Science",
    qualification: "MCA",
    experience: 6,
    department: "Computer",
    designation: "Teacher",
    salary: 50000,
    joiningDate: "2021-07-01",
    status: "active",
  },
];

export const feePayments: FeePayment[] = [
  {
    id: "1",
    studentId: "1",
    studentName: "Aarav Sharma",
    class: "8-A",
    amount: 25000,
    paidAmount: 25000,
    status: "paid",
    paymentDate: "2025-06-05",
    paymentMethod: "upi",
    receiptNo: "REC-2025-001",
    dueDate: "2025-06-10",
  },
  {
    id: "2",
    studentId: "2",
    studentName: "Ananya Gupta",
    class: "9-B",
    amount: 28000,
    paidAmount: 15000,
    status: "partial",
    paymentDate: "2025-06-08",
    paymentMethod: "online",
    receiptNo: "REC-2025-002",
    dueDate: "2025-06-10",
  },
  {
    id: "3",
    studentId: "3",
    studentName: "Rohan Patel",
    class: "8-A",
    amount: 25000,
    paidAmount: 25000,
    status: "paid",
    paymentDate: "2025-06-03",
    paymentMethod: "bank_transfer",
    receiptNo: "REC-2025-003",
    dueDate: "2025-06-10",
  },
  {
    id: "4",
    studentId: "4",
    studentName: "Ishita Verma",
    class: "7-C",
    amount: 22000,
    paidAmount: 0,
    status: "overdue",
    dueDate: "2025-05-10",
  },
  {
    id: "5",
    studentId: "5",
    studentName: "Kabir Singh",
    class: "10-A",
    amount: 30000,
    paidAmount: 0,
    status: "pending",
    dueDate: "2025-07-10",
  },
];

export const attendanceRecords: AttendanceRecord[] = [
  { id: "1", studentId: "1", studentName: "Aarav Sharma", class: "8", section: "A", date: "2025-06-28", status: "present", markedBy: "Dr. Meena Agarwal" },
  { id: "2", studentId: "2", studentName: "Ananya Gupta", class: "9", section: "B", date: "2025-06-28", status: "present", markedBy: "Rajendra Kumar" },
  { id: "3", studentId: "3", studentName: "Rohan Patel", class: "8", section: "A", date: "2025-06-28", status: "absent", markedBy: "Dr. Meena Agarwal", remarks: "Sick leave" },
  { id: "4", studentId: "4", studentName: "Ishita Verma", class: "7", section: "C", date: "2025-06-28", status: "late", markedBy: "Sunita Joshi" },
  { id: "5", studentId: "5", studentName: "Kabir Singh", class: "10", section: "A", date: "2025-06-28", status: "present", markedBy: "Amit Rathore" },
];

export const communications: Communication[] = [
  {
    id: "1",
    title: "Summer Vacation Notice",
    message: "School will remain closed from July 1 to July 15 for summer vacation.",
    type: "push",
    audience: "All Parents",
    sentAt: "2025-06-20 10:00",
    sentBy: "Principal",
    readCount: 2450,
    totalRecipients: 2847,
    status: "sent",
  },
  {
    id: "2",
    title: "Fee Payment Reminder",
    message: "Kindly clear pending fees before June 30 to avoid late fee charges.",
    type: "sms",
    audience: "Parents with Pending Fees",
    sentAt: "2025-06-25 09:00",
    sentBy: "Accounts",
    readCount: 890,
    totalRecipients: 1234,
    status: "sent",
  },
  {
    id: "3",
    title: "Annual Day Event",
    message: "Annual Day celebration on July 20. All parents are invited.",
    type: "whatsapp",
    audience: "All",
    sentAt: "",
    sentBy: "Admin",
    readCount: 0,
    totalRecipients: 5000,
    status: "scheduled",
  },
];

export const admissions: Admission[] = [
  {
    id: "1",
    studentName: "Priya Meena",
    parentName: "Rakesh Meena",
    email: "rakesh@email.com",
    phone: "+91 9876500001",
    class: "6",
    previousSchool: "Government School, Ajmer",
    status: "applied",
    appliedDate: "2025-06-15",
    source: "website",
  },
  {
    id: "2",
    studentName: "Arjun Jain",
    parentName: "Sunil Jain",
    email: "sunil@email.com",
    phone: "+91 9876500002",
    class: "3",
    status: "interview",
    appliedDate: "2025-06-18",
    source: "referral",
  },
  {
    id: "3",
    studentName: "Sneha Yadav",
    parentName: "Mohan Yadav",
    email: "mohan@email.com",
    phone: "+91 9876500003",
    class: "1",
    status: "accepted",
    appliedDate: "2025-06-10",
    source: "walk_in",
  },
  {
    id: "4",
    studentName: "Vikash Rathore",
    parentName: "Dinesh Rathore",
    email: "dinesh@email.com",
    phone: "+91 9876500004",
    class: "8",
    previousSchool: "Ryan International",
    status: "enquiry",
    appliedDate: "2025-06-27",
    source: "social_media",
  },
];

export const timetableEntries: TimetableEntry[] = [
  { id: "1", day: "Monday", period: 1, startTime: "08:00", endTime: "08:45", subject: "Mathematics", teacher: "Dr. Meena Agarwal", class: "8", section: "A", room: "101" },
  { id: "2", day: "Monday", period: 2, startTime: "08:45", endTime: "09:30", subject: "English", teacher: "Sunita Joshi", class: "8", section: "A", room: "101" },
  { id: "3", day: "Monday", period: 3, startTime: "09:45", endTime: "10:30", subject: "Physics", teacher: "Rajendra Kumar", class: "8", section: "A", room: "Lab-1" },
  { id: "4", day: "Monday", period: 4, startTime: "10:30", endTime: "11:15", subject: "Computer Science", teacher: "Amit Rathore", class: "8", section: "A", room: "Computer Lab" },
  { id: "5", day: "Monday", period: 5, startTime: "11:30", endTime: "12:15", subject: "Hindi", teacher: "Rajendra Kumar", class: "8", section: "A", room: "101" },
  { id: "6", day: "Monday", period: 6, startTime: "12:15", endTime: "13:00", subject: "Social Science", teacher: "Sunita Joshi", class: "8", section: "A", room: "101" },
];

export const exams: Exam[] = [
  { id: "1", name: "Mid-Term Examination", type: "midterm", class: "8", subject: "Mathematics", date: "2025-07-15", startTime: "09:00", duration: 180, maxMarks: 100, passingMarks: 33, status: "scheduled" },
  { id: "2", name: "Mid-Term Examination", type: "midterm", class: "8", subject: "English", date: "2025-07-16", startTime: "09:00", duration: 180, maxMarks: 100, passingMarks: 33, status: "scheduled" },
  { id: "3", name: "Unit Test - 2", type: "unit_test", class: "9", subject: "Physics", date: "2025-07-05", startTime: "10:00", duration: 90, maxMarks: 50, passingMarks: 17, status: "scheduled" },
  { id: "4", name: "Quiz - Chapter 5", type: "quiz", class: "10", subject: "Computer Science", date: "2025-06-30", startTime: "11:00", duration: 30, maxMarks: 20, passingMarks: 8, status: "scheduled" },
];

export const revenueData = [
  { month: "Jan", revenue: 2800000, collected: 2450000 },
  { month: "Feb", revenue: 2900000, collected: 2600000 },
  { month: "Mar", revenue: 3100000, collected: 2850000 },
  { month: "Apr", revenue: 3400000, collected: 3100000 },
  { month: "May", revenue: 3200000, collected: 2900000 },
  { month: "Jun", revenue: 3500000, collected: 3200000 },
];

export const attendanceData = [
  { day: "Mon", present: 94.2, absent: 5.8 },
  { day: "Tue", present: 92.8, absent: 7.2 },
  { day: "Wed", present: 95.1, absent: 4.9 },
  { day: "Thu", present: 93.5, absent: 6.5 },
  { day: "Fri", present: 88.7, absent: 11.3 },
  { day: "Sat", present: 91.2, absent: 8.8 },
];
